theme: minima
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #box1{
            width: 50px;
            height: 50px;
            background-color: green;
            margin: 10px;
        }
        #box2{
            width: 100px;
            height:100px;
            background-color: grey;
            display: none;
        }
    </style>
    <script>
         window.onload=function(){
             var oBox1=document.getElementById('box1');
             var oBox2=document.getElementById('box2');
             var timer=null;
             oBox2.onmouseover=oBox1.onmouseover=function(){
                 clearTimeout(timer);
                 oBox2.style.display='block';
             };
             oBox2.onmouseout=oBox1.onmouseout=function(){
                 timer=setTimeout(function(){
                     oBox2.style.display='none';
                 },500);
             };
         };
    </script>
</head>
<body>
<div id="box1">

</div>
<div id="box2">
    <p>你好我是张先生</p>
</div>
</body>
</html>
